language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: L2NPOp8mCuBuvEwwlqeNvbQzyF2ANJ1TKHNhO80jPUlko1UZOGUswvjVqR8QwnLnSfmg4b1L6KSS/2LCaju5PoRmJMD6cUO5wqHNNFoXejVFtAcD02v081yQFXhl3Lf9oS8kFXZ6HnaS7rpHFS8yb2HSdsavRf3oaioxjBefMCrj+8wcNtermyA7hHLj3uge3F/NbTtFh2YwD4hK/gQljrN5Klo1Qdvg3bSO9/SS+f3T+k9wjllsIxSeTAXHfEeOukxjMNvwxLJ+xaw53K/2jwJNEx5LPSkl6MsUBvTWKi1pXaeUcyOZQB2CCeCXdGyfv+FPmPrR+SRDqOm9J/aUv/6dvQeRBwodjalZSHu9cvwGe9pAVwqSl/wsX45yaILV+zrWdBjfI3Xh7nynDg/QMvso1Wvyrm8rd80xlfbknEZXuB7FqbOl/XVCT1wASpB3/YpDuDE3ASj8a+8tiRyn9M6OPhRJStpEGXhk8DIC1oq4gMoraUcRtRsqeXjk6USEM6YUTyvIfp91jGrRlxGduU6opKat5cmOzAfBNHLrUvXNMfDjVCY0F4yuDaT5Swoc1Hz68iMtsTQIqY6pfiqqnB1RMwaTOY/6pF6aKQYhAJdV86xXsZSInWg0GhWrXnWsJbkjoJXhLX5kTAzijvfbM3QqgbG5sAC8lZTlFETCu/w=
